commandChecking: true
swears:
- fuck
- shit
- crap
- wank
- cunt
- crap
- ass
exception:
- glass
ChatMessage: I <3 MilSpec!
CustomWordActions:
- lag-Saying lag is annoying-kick <player>
AdvertiserPunishment:
- broadcast I hate you <player>
Advertisers:
- debug-3
- test-7