aggressive: true
DisableSwearing: false
commandChecking: true
swears:
- fuck
- shit
- crap
- wank
- cunt
- crap
- ass
exception:
- glass
ChatMessage: I <3 MilSpec!
CustomWordActions:
- lag-Saying lag is annoying-kick <player>
