aggressive: true
numberofgroups: 5
DisableSwearing: false
commandChecking: true
swears:
- fuck
- shit
- crap
- wank
- cunt
- crap
- ass
forbiddenGroup1:
- lag
Group1Message:

forbiddenGroup2:

Group2Message:

forbiddenGroup3:

Group3Message:

exception:
- glass

ChatMessage: I <3 MilSpec!

CustomWordActions:
- lag-Saying lag is annoying-kick <player>
